(part "B02P-XL-HDS___LF__SN_"
    (packageRef "SHDR2W120P580X500_2X1_790X1380X1460P")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "JST (JAPAN SOLDERLESS TERMINALS)")
    (property "Manufacturer_Part_Number" "B02P-XL-HDS  (LF)(SN)")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "JST, XL, 2 Way, 2 Row, Top Entry PCB Header")
    (property "Datasheet_Link" "http://uk.rs-online.com/web/p/products/1856766")
    (property "symbolName1" "B02P-XL-HDS___LF__SN_")
)
