(part "LC-04T"
    (packageRef "LC04T")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "JST (JAPAN SOLDERLESS TERMINALS)")
    (property "Manufacturer_Part_Number" "LC-04T")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "LC-04T")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/lc-04t/jst-manufacturing")
    (property "Description" "Wire-To-Board Connector, Shrouded, Top Entry, LC Series, Crimp, Header, 4, 5.08 mm RoHS Compliant: Yes")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/LC-04T.pdf")
    (property "symbolName1" "LC-04T")
)
