(part "STPS1045B"
    (packageRef "T405600BTR")
    (interface
        (port "1" (symbPinId 1) (portName "A") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NOPAD") (portType INOUT))
        (port "3" (symbPinId 3) (portName "A_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "K") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "STPS1045B")
    (property "Mouser_Part_Number" "511-STPS1045B")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/STPS1045B?qs=Aez0sHNrW%2FWlppnqb0KZhw%3D%3D")
    (property "Arrow_Part_Number" "STPS1045B")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/stps1045b/stmicroelectronics?utm_currency=USD&region=europe")
    (property "Description" "Schottky barrier diode,STPS1045B 10A 45V STMicroelectronics STPS1045B Schottky Diode, 10A, 45V, 3-Pin D-PAK")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/stps1045b.pdf")
    (property "symbolName1" "STPS1045B")
)
