(part "OPT3001IDNPRQ1"
    (packageRef "SON65P200X200X65-7N-D")
    (interface
        (port "1" (symbPinId 1) (portName "VDD") (portType INOUT))
        (port "2" (symbPinId 2) (portName "ADDR") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SCL") (portType INOUT))
        (port "5" (symbPinId 5) (portName "INT") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SDA") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "OPT3001IDNPRQ1")
    (property "Mouser_Part_Number" "595-OPT3001IDNPRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/OPT3001IDNPRQ1?qs=u4fy%2FsgLU9PFQBSq8%2FiUeQ%3D%3D")
    (property "Arrow_Part_Number" "OPT3001IDNPRQ1")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/opt3001idnprq1/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "Ambient Light Sensors Automotive Digital Ambient Light Sensor (ALS) With High-Precision Human-Eye Response 6-USON -40 to 85")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/opt3001-q1.pdf")
    (property "symbolName1" "OPT3001IDNPRQ1")
)
