(part "AD7414ARTZ-1REEL7"
    (packageRef "SOT95P280X145-6N")
    (interface
        (port "1" (symbPinId 1) (portName "AS") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VDD") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SCL") (portType INOUT))
        (port "5" (symbPinId 5) (portName "ALERT") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SDA") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "AD7414ARTZ-1REEL7")
    (property "Mouser_Part_Number" "584-AD7414ARTZ-1R7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/AD7414ARTZ-1REEL7?qs=NmRFExCfTkEOVHQ3uEvF5g%3D%3D")
    (property "Arrow_Part_Number" "AD7414ARTZ-1REEL7")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ad7414artz-1reel7/analog-devices?region=nac")
    (property "Description" "10-bit temperature-to-digital converter  Temperature range: 40C to +125C  Typical accuracy of +/-0.5C at +40C  SMBus/I2C-compatible serial interface  3 A power-down current  Temperature conversion time: 29 s typ  Space-saving 6-lead (AD7414) and 5-lead (AD7415)  SOT-23 packages  Pin selectable addressing via AS  Overtemperature indicator (AD7414 Only)  SMBus alert function (AD7414 only)  4 versions allow 8 I2C addresses (AD7414)  2 versions allow 6 I2C addresses (AD7415)")
    (property "Datasheet_Link" "https://www.analog.com/media/en/technical-documentation/data-sheets/AD7414_7415.pdf")
    (property "symbolName1" "AD7414ARTZ-1REEL7")
)
